# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ACIDS-IRCAM 
email: acids.ircam@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Artificial Creative Intelligence and Data Science (ACIDS) group is part of the RepMus team 
  at IRCAM laboratory and is hell-bent on trying to model musical creativity by developing innovative 
  artificial intelligence models.
#baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://acids-ircam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: acids.ircam0
instagram_username: acids_ircam
github_username: acids-ircam 
# relative_permalinks: false
header_pages: ['projects.markdown', 'articles.md', 'music.markdown', 'workshops/index.md', 'team.markdown']

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  date_format: "%b %-d, %Y"

include: ['/workshops', '/workshops/nime2022']

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
